# Generated by Django 6.0.4 on 2026-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=50)),
                ('equipo_visitante', models.CharField(max_length=50)),
                ('fecha_partido', models.DateTimeField()),
                ('jornada', models.IntegerField()),
                ('grupo', models.CharField(blank=True, max_length=5, null=True)),
                ('fase', models.CharField(choices=[('GRUPOS', 'Grupos'), ('OCTAVOS', 'Octavos'), ('CUARTOS', 'Cuartos'), ('SEMIS', 'Semifinales'), ('FINAL', 'Final')], max_length=20)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('clasificado', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_clasificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
    ]
