# Generated by Django 6.0.4 on 2026-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fase',
            field=models.CharField(choices=[('GRUPOS', 'Grupos'), ('DIECISEISAVOS', 'Dieciseisavos'), ('OCTAVOS', 'Octavos'), ('CUARTOS', 'Cuartos'), ('SEMIS', 'Semifinales'), ('FINAL', 'Final')], max_length=20),
        ),
    ]
