# Generated by Django 6.0.4 on 2026-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='numero_llave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fase',
            field=models.CharField(choices=[('GRUPOS', 'Grupos'), ('DIECISEISAVOS', 'Dieciseisavos'), ('OCTAVOS', 'Octavos'), ('CUARTOS', 'Cuartos'), ('SEMIS', 'Semifinales'), ('TERCER_PUESTO', 'Tercer Puesto'), ('FINAL', 'Final')], max_length=20),
        ),
    ]
