# Generated by Django 6.0.4 on 2026-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_numero_llave_alter_match_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='metodo_clasificacion',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Tiempo Regular'), ('PRORROGA', 'Prórroga'), ('PENALES', 'Penales')], max_length=20, null=True),
        ),
    ]
